/// Uses MyriadInlineGeneration: the generated code is appended to
/// the end of this module without namespace or opens. As the module is rec, it can be used above that.
module rec Orsak.Myriad.Showcase.Inline

open System
open Orsak
open Orsak.Myriad

[<GenEffects>]
type IClock =
    abstract Now: unit -> DateTimeOffset

type IGreeter =
    abstract Greet: string -> string

type IGreeterProvider =
    abstract Effect: IGreeter

/// An ad hoc environment, inheriting IClockProvider, which is generated further down this file.
[<GenEnvironment>]
type IInlineEnvironment =
    inherit IClockProvider
    inherit IGreeterProvider

let greet name =
    Effect.Create(fun (provider: #IGreeterProvider) -> provider.Effect.Greet name)

/// Uses the generated InlineEnvironment.create, declared below. Its signature is fully annotated, so the
/// rec module can use it above its declaration; generated effect functions like Clock.now are inferred,
/// so they are used from a later file instead (Program.fs).
let environment () =
    InlineEnvironment.create {|
        Clock = { new IClock with member _.Now() = DateTimeOffset(2026, 9, 23, 12, 0, 0, TimeSpan.Zero) }
        Greeter = { new IGreeter with member _.Greet name = $"Hello {name}" }
    |}
//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
type IClockProvider =
    abstract Effect: IClock

module Clock =
    let now () =
        Effect.Create(fun (er: #IClockProvider) -> er.Effect.Now())


module InlineEnvironment =
    let create (effects: {| Clock: IClock; Greeter: IGreeter |}) : IInlineEnvironment =
        { new IInlineEnvironment

          interface IClockProvider with
              member _.Effect = effects.Clock
          interface IGreeterProvider with
              member _.Effect = effects.Greeter
        }

    let run effects = Effect.run (create effects)
    let runOrFail effects = Effect.runOrFail (create effects)
