name: Build and Test

on: 
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'samples/**'
      - 'experiments/**'
      - 'README.md'
      - 'CHANGELOG.md'

  push:
    tags:
      - '*'
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'samples/**'
      - 'experiments/**'
      - 'README.md'
      - 'CHANGELOG.md'
jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x


      - name: Setup .NET Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Setup .NET Core 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore tools
        run: dotnet tool restore

      - name: Set version
        run: |
          dotnet gitversion /updateprojectfiles /output json > $HOME/version.json
          echo "GITVERSION=$(jq -c . < $HOME/version.json)" >> $GITHUB_ENV

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test

      - name: Pack NuGet package
        if: ${{ success() && github.event_name != 'pull_request' }}
        run: dotnet pack --configuration Release --output ./nupkg

      - name: Push generated package to GitHub registry
        if: ${{ success() && github.event_name != 'pull_request' }}
        run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json -SkipDuplicate